name: Other Branch All Tests

on: [push]

jobs:
  run_all_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
      - name: Run TEST
        run:
          pytest
